<a href="https://colab.research.google.com/github/SrivinaySridhar/PY4AIML/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Numpy


### Exercise 01: Form an array using np.arange which contains all even numbers. 10 to 30


In [2]:
#your code here

import numpy as np

nums_arr = np.arange(10, 31)
even_nums_arr = nums_arr[nums_arr % 2 == 0]
print("Array containing all even numbers from 10 to 30: \n", even_nums_arr)

Array containing all even numbers from 10 to 30: 
 [10 12 14 16 18 20 22 24 26 28 30]


Alternative:

In [3]:
even_numb_arr = np.arange(10, 31, 2)
print("Array containing all even numbers from 10 to 30: \n", even_numb_arr)

Array containing all even numbers from 10 to 30: 
 [10 12 14 16 18 20 22 24 26 28 30]


### Exercise 02: Create an array of evenly spaced numbers upto 24 as one dimentional and reshape it to (2,4,3)

In [4]:
#your code here

one_dim_arr = np.arange(0, 24)
print("Reshaped array: \n", one_dim_arr.reshape(2,4,3))

Reshaped array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


### Exercise 03: Get [1, 4, 5] from [[1, 2], [3, 4], [5, 6]] using indexing

In [5]:
#your code here

given_arr = np.array([[1,2], [3,4], [5,6]])
print("Given array: \n", given_arr, "\n")
to_get = [given_arr[0][0], given_arr[1][1], given_arr[2][0]]
print("Required values:", to_get)

Given array: 
 [[1 2]
 [3 4]
 [5 6]] 

Required values: [1, 4, 5]


### Exercise 04: From the given array [[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]] form an array containing elements greater than 5

In [6]:
#your code here

given_array = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print("Given array: \n", given_array, "\n")
five_up = given_array[given_array > 5]
print("Array containing elements greater than 5: \n", five_up)

Given array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

Array containing elements greater than 5: 
 [ 6  7  8  9 10 11]


### Exercise 05: Add given two arrays [[ 0.0, 0.0, 0.0],[10.0,10.0,10.0], [20.0,20.0,20.0],[30.0,30.0,30.0]] and [1.0,2.0,3.0]

In [7]:
#your code here

given_array1 = np.array([[0.0, 0.0, 0.0], [10.0, 10.0 ,10.0], [20.0, 20.0, 20.0], [30.0, 30.0, 30.0]])
given_array2 = np.array([1.0, 2.0, 3.0])
sum = given_array1 + given_array2
print("Sum of the given arrays: \n", sum)

Sum of the given arrays: 
 [[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


### Exercise 06: Multiplication of two arrays [1,2,3,4] [10,20,30,40]

In [8]:
#your code here

given_arr1 = np.array([1, 2, 3, 4])
given_arr2 = np.array([10, 20, 30, 40])
product = given_arr1 * given_arr2
print("Product of the given arrays:", product)

Product of the given arrays: [ 10  40  90 160]


### Exercise 07: Transpose the given array [[0,1,2,3] [4,5,6,7] [8,9,10,11]]

In [9]:
#your code here

given__array = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print("Given array: \n", given__array, "\n")
transposed_array = given__array.T
print("Transpose of given array: \n", transposed_array)

Given array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Transpose of given array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### Exercise 08: Concatenate [[1,2],[3,4]] and [[5,6],[7,8]] using numpy in axis 1

In [10]:
#your code here

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7,8]])
concatenated_array = np.concatenate((arr1, arr2), axis = 1)
print("Concatenated array: \n", concatenated_array)

Concatenated array: 
 [[1 2 5 6]
 [3 4 7 8]]


Alterative:

In [11]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7,8]])
concatenated_array = np.hstack((arr1, arr2))
print("Concatenated array: \n", concatenated_array)

Concatenated array: 
 [[1 2 5 6]
 [3 4 7 8]]


### Exercise 9: Given a Multidimensional array find the following,


1.   get second and third coloum from the given Multidimensional array
2.   get second and third row from the given Multidimensional array
3.   and reverse the given Multidimensional array


In [12]:
import numpy as np
array2D = np.array([['a', 'b', 'c'], ['d', 'e', 'f'], ['g', 'h', 'i']])
#Your code here

answer_1 = array2D[:,1:]
print("Answer 1: 2nd and 3rd column \n", answer_1, "\n")
answer_2 = array2D[1:]
print("Answer 2: 2nd and 3rd row \n", answer_2, "\n")
answer_3 = np.flip(array2D)
print("Answer 3: Reversed array \n",answer_3)

Answer 1: 2nd and 3rd column 
 [['b' 'c']
 ['e' 'f']
 ['h' 'i']] 

Answer 2: 2nd and 3rd row 
 [['d' 'e' 'f']
 ['g' 'h' 'i']] 

Answer 3: Reversed array 
 [['i' 'h' 'g']
 ['f' 'e' 'd']
 ['c' 'b' 'a']]


## Exercise 10: Given a Multidimensional array find the following,


1.   What is the average value of the second column
2.   Calculate the Mean of the given Multidimensional array



In [13]:
import numpy as np
array5D = np.array([[174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [476442,  35455, 191553, 384154,  29917]])
#Your code here

column_arr = array5D[:,1:2]
answer1 = np.average(column_arr)
print("The average value of the second column is:", answer1 , "\n")
answer2 = np.mean(array5D)
print("The mean value of the given multidimensional array", answer2)

The average value of the second column is: 234002.6 

The mean value of the given multidimensional array 243617.52


### Exercise 11: For the given array, get the slice of the first row and display them.

In [14]:
array2 = np.array([[[22, 23, 24], [25, 26, 27], [28, 29, 30]],
               [[31, 32, 33], [34, 35, 36], [37, 38, 39]],
               [[40, 41, 42], [43, 44, 45], [46, 47, 48]]])

##your code here

firstRow_arr = array2[:,:1]
print("First row of array2: \n", firstRow_arr)

First row of array2: 
 [[[22 23 24]]

 [[31 32 33]]

 [[40 41 42]]]


### Exercise 12: Create a 10x10 array with random values and find minimum and maximum number along axis 1

In [16]:
#your code here

array10D = np.random.randint(1000, size = (10,10))
print("Random array: \n", array10D, "\n")

min_axis1 = np.min(array10D, axis = 1)
print("Minimum numbers along axis 1: \n", min_axis1, "\n")

max_axis1 = np.max(array10D, axis = 1)
print("Maximum numbers along axis 1: \n", max_axis1)

Random array: 
 [[938 138 706 319 586 158 740 612 845 238]
 [488 539 980 889 639 519 483 952 871  61]
 [706 316 212  35 336 154 166 814 921 148]
 [118 551 352 100 596 722 694 201 174 228]
 [207 665 739 853 200 675  14 772 367  68]
 [404  81 822 719 890 995 176 513 236 873]
 [874 920  18 587  88 264 961 225 627 105]
 [ 26  94 961 800 224 186  48 715 646  49]
 [486 914 953 983 219  79 120 292 583 448]
 [544 195 703 364 313 218 207 858 548 846]] 

Minimum numbers along axis 1: 
 [138  61  35 100  14  81  18  26  79 195] 

Maximum numbers along axis 1: 
 [938 980 921 722 853 995 961 961 983 858]


*italicized text*### Exercise 13: Create an array of the first 20 odd integers

In [17]:
### your code here

odd_int_arr = np.arange(1, 41, 2)
print("The following array holds the first", len(odd_int_arr), "odd integers:", odd_int_arr)

The following array holds the first 20 odd integers: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


### Exercise 14: Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [18]:
### your code here

diag5D_arr = np.diag([1, 2, 3, 4], k = -1)
print("A 5x5 matrix with values 1, 2, 3, 4 just below the diagonal:\n", diag5D_arr)

A 5x5 matrix with values 1, 2, 3, 4 just below the diagonal:
 [[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### Exercise 15: 2x+3y=13 3x+y=9 find the value of x and y.

In [19]:
### your code here

import sympy as sym
x = sym.Symbol("x")
y = sym.Symbol("y")

solution = sym.solve((x*2 + y*3 - 13, x*3 + y - 9), (x, y))
solution[x], solution[y]

(2, 3)

Alternative:

In [20]:
x = np.array([[2,3], [3,1]])
y = np.array([13, 9])
sol = np.linalg.solve(x, y)
print(list(sol))

[2.0, 3.0]


### Exercise 16: Compute $e^x$, element-wise for a sample array

In [25]:
### your code here
example_arr = np.array([1, 4, 9, 16])
answers = np.exp(example_arr)
answers

array([2.71828183e+00, 5.45981500e+01, 8.10308393e+03, 8.88611052e+06])